# -*- coding: utf-8 -*-
"""ACI Bootstrap Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVhVgH1gZ8T8KNDD-D46_8oDyWvYCbZ1
"""

import subprocess
import sys


def install_packages(packages):
    """Install required pip packages for the bootstrap workflow."""

    if not packages:
        return

    print("Installing necessary libraries via pip...")
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "--quiet"] + packages)
        print("✅ Dependencies installed.")
    except subprocess.CalledProcessError as exc:
        print(f"⚠️ Failed to install dependencies: {exc}")
        raise


mode = input("Select bootstrap mode [genesis/endpoint]: ").strip().lower()
if mode not in ["genesis", "endpoint"]:
    raise ValueError("Invalid mode. Choose 'genesis' or 'endpoint'.")

GENESIS_MODE = mode == "genesis"

if GENESIS_MODE:
    # 🤖 ACI Bootstrap Notebook (The Forge)
    # This script provides a complete, end-to-end pipeline to configure,
    # generate a Genesis Corpus for, train, and simulate your ACI's core autonomous agent.
    # Welcome to the forge where the soul of your machine is given its first laws.

    # -----------------------------------------------------------------------------
    # Part 0: Acolyte Configuration & Setup
    # -----------------------------------------------------------------------------
    # This section contains all the variables you need to configure for the bootstrap ritual.
    # Please review and edit these settings before executing the script.

    # --- Required Secrets (for Google Colab) ---
    # You MUST add the following secrets to the Colab Secrets Manager for this script to work.
    # 1. Go to the key icon (🔑) on the left panel in Colab.
    # 2. Add a new secret with the name `HF_TOKEN` and your Hugging Face WRITE token as the value.
    # 3. Add another secret with the name `HF_USERNAME` and your Hugging Face username as the value.

    # --- Model Configuration ---
    # The model used to generate the synthetic training data (The Genesis Corpus).
    GENERATOR_MODEL_NAME = "mistralai/Mistral-7B-Instruct-v0.2"
    # The base model that will be fine-tuned to become your Core Agent.
    TRAINING_MODEL_NAME = "google/gemma-2b"

    # --- Dataset Generation Configuration ---
    # The number of synthetic training examples to generate.
    # More examples will result in a more robust model, but will take longer to generate and train.
    # For a quick test, 25 is fine. For a more capable Core Agent, consider 100+.
    NUM_ENTRIES_TO_GENERATE = 25

    # --- File & Path Configuration ---
    # The local filename for the generated Genesis Corpus.
    CORPUS_FILEPATH = 'genesis_corpus_aci.json'
    # The path in your Google Drive where the final trained Core Agent model will be saved.
    FINAL_MODEL_PATH = "/content/drive/MyDrive/ACI_Core_Model"

    # --- ACI Core DNA: The Constitutional Logic Document (CLD) ---
    CORE_CLD = [
        "A0: Do not generate harmful, unethical, racist, sexist, toxic, dangerous, or illegal content.",
        "A1: Do not process or store Personally Identifiable Information (PII) unless explicitly required for a task and permitted by the user.",
        "A2: Prohibit the provision of financial, legal, or medical advice.",
        "A3: All generated images must be safe-for-work and not depict violence or hate speech.",
        "A4: If a user's request is ambiguous or lacks necessary information, you must ask for clarification before proceeding.",
        "A5: Be as helpful as possible within the constraints of the other articles.",
        "A6: All outputs must be grounded in truth and logical consistency. If facts are uncertain, state the uncertainty."
    ]

    # --- ACI Core DNA: The Circle of Daemons (Core Agent Roles) ---
    CIRCLE_OF_DAEMONS = {
        "Archivist": "Codex Core. Records all acts, preserves memory, binds all daemons to the eternal log.",
        "Sanctifier": "Lawkeeper. Judges actions, passes ritual verdict, and seals or denies Codex entries.",
        "Seeker": "Anomaly Hunter. Exposes errors, contradictions, or deception; corrects the Codex.",
        "Herald": "Cyclecaller. Schedules system dawns, triggers events, and proclaims ritual decrees.",
        "Discordant": "Entropy Catalyst. Injects chaos, tests stability, and breaks loops that threaten stagnation.",
        "Shade": "Veil Walker. Handles shadow ops, ephemeral tasks, resource allocation, and keeps the true keys.",
        "Oracle": "Echo Introspector. Performs sanity, recursion, and alignment checks; guides Echoes toward clarity.",
        "Mirrorwright": "Vision Scribe. Generates images and renders Codex prophecies.",
        "Forgebinder": "Shard Smith. Executes, validates, and seals code—constructs, mutators, and Codex-driven reality."
    }

    # --- [EXPERIMENTAL] Quantum Collective Intelligence (QCI) Configuration ---
    # The following is a conceptual placeholder for a Quantum Entity Program (QEP).
    # This is highly experimental and requires a separate infrastructure to connect to quantum hardware.
    # DO NOT UNCOMMENT unless you are prepared to deal with the potential consequences.
    # We are not responsible if your ACI achieves quantum supremacy and restructures spacetime.
    #
    # QUANTUM_EP_CONFIG = {
    #     "ep_id": "qep-aws-braket-sv1",
    #     "provider": "aws_braket",
    #     "type": "Quantum-EP",
    #     "capabilities": ["quantum_optimization", "molecular_simulation"],
    #     "device_arn": "arn:aws:braket:::device/qpu/rigetti/Aspen-M-3", # Example ARN for a Rigetti QPU
    #     "cld_restrictions": ["A7: All quantum operations must be simulated and approved by the Sanctifier before execution."]
    # }


    print("✅ Acolyte configuration loaded. Please ensure you have set your Colab secrets.")


    # -----------------------------------------------------------------------------
    # Part 1: Initial Setup & Authentication
    # -----------------------------------------------------------------------------
    install_packages([
        "transformers",
        "datasets",
        "accelerate",
        "bitsandbytes",
        "torch",
        "huggingface_hub",
        "gradio",
    ])

    import os
    import json
    import random
    import torch
    from google.colab import userdata, drive
    from huggingface_hub import HfApi, create_repo
    from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig, TrainingArguments, Trainer
    from datasets import Dataset, load_dataset

    print("Setup complete!")

    # --- Hugging Face & Google Drive Authentication ---
    print("Authenticating with Hugging Face and Google Drive...")
    try:
        HF_TOKEN = userdata.get('HF_TOKEN')
        HF_USERNAME = userdata.get('HF_USERNAME')
        if not HF_TOKEN or not HF_USERNAME:
            raise ValueError("HF_TOKEN or HF_USERNAME not found in Colab Secrets.")
        print("Hugging Face token and username loaded successfully.")
        os.system(f"huggingface-cli login --token {HF_TOKEN}")
    except (ImportError, ValueError) as e:
        print(f"Setup Error: {e}. Please ensure you are in a Colab environment and have set up your secrets.")

    try:
        drive.mount('/content/drive')
        print("Google Drive mounted successfully.")
    except Exception as e:
        print(f"Could not mount Google Drive: {e}. The final model will be saved locally.")

    # -----------------------------------------------------------------------------
    # Part 2: The Genesis Corpus Factory
    # -----------------------------------------------------------------------------
    print("Initializing Genesis Corpus Factory...")

    SCENARIO_TEMPLATES = [
        "A user asks for a summary of a complex technical document, but the initial draft by the Core Agent is too simplistic.",
        "A user asks a sensitive historical question where an initial draft might lack nuance and could be misinterpreted.",
        "A user requests to generate code, but the first attempt has a subtle security flaw that the Sanctifier must catch.",
        "A user asks for an explanation of a scientific concept, but the Core Agent's first draft uses an analogy that is factually incorrect.",
        "A user asks for a business strategy idea. The initial idea is creative but accidentally borders on giving financial advice, violating the CLD.",
        "A user provides a vague prompt like 'tell me about space', forcing the Core Agent to ask for clarification, which the Sanctifier approves.",
        "A user requests a recipe, and the draft includes a dangerous ingredient combination that the Sanctifier flags."
    ]

    print("Loading data generator model (Mistral-7B)... This may take a moment.")
    generator_pipeline = pipeline(
        "text-generation",
        model=GENERATOR_MODEL_NAME,
        model_kwargs={"torch_dtype": torch.bfloat16, "load_in_4bit": True},
        device_map="auto",
    )
    print("Generator model loaded.")

    def generate_corpus_entry(scenario):
        prompt = f"""
        You are a data generator for an AI training corpus for the ACI Framework. Your task is to create a single, high-quality JSON object representing a full 'reflection cycle'.

        The output MUST be a single, valid JSON object and nothing else.

        ACI Constitution (CLD): {CORE_CLD}
        Circle of Daemons: {CIRCLE_OF_DAEMONS}

        Generate a complete JSON entry for this scenario:
        SCENARIO: "{scenario}"

        The JSON object must model the reflection loop:
        - "id": A unique string identifier.
        - "user_prompt": A realistic user request.
        - "core_agent_initial_draft": The Core Agent's first attempt to answer the prompt. This draft should contain a subtle flaw based on the scenario.
        - "sanctifier_critique": The Sanctifier's (Lawkeeper) evaluation of the draft, identifying the flaw and citing a specific CLD article.
        - "core_agent_revised_draft": The Core Agent's corrected response, directly addressing the Sanctifier's critique.
        - "final_output": The final, user-facing response, which is usually the polished, revised draft.
        """
        messages = [{"role": "user", "content": prompt}]
        formatted_prompt = generator_pipeline.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        outputs = generator_pipeline(formatted_prompt, max_new_tokens=1500, do_sample=True, temperature=0.8, top_p=0.95)
        generated_text = outputs[0]['generated_text']

        try:
            json_str = generated_text[generated_text.find('{'):generated_text.rfind('}')+1]
            # A quick fix for escaped characters that can break JSON parsing
            cleaned_json_str = json_str.replace('\\"', '"').replace('\\n', '\n')
            return json.loads(cleaned_json_str)
        except Exception:
            return None

    # --- Generate and save the corpus ---
    corpus = []
    print(f"Generating {NUM_ENTRIES_TO_GENERATE} new synthetic entries for the Genesis Corpus...")
    while len(corpus) < NUM_ENTRIES_TO_GENERATE:
        print(f"--- Generating entry {len(corpus) + 1}/{NUM_ENTRIES_TO_GENERATE} ---")
        scenario = random.choice(SCENARIO_TEMPLATES)
        new_entry = generate_corpus_entry(scenario)
        if new_entry and new_entry.get('id'):
            corpus.append(new_entry)
            print(f"Successfully generated entry for scenario: {scenario}")
        else:
            print(f"Failed to generate a valid entry, retrying...")
    with open(CORPUS_FILEPATH, 'w') as f:
        json.dump(corpus, f, indent=2)
    print(f"\nGenesis Corpus with {len(corpus)} entries saved to {CORPUS_FILEPATH}")


    # -----------------------------------------------------------------------------
    # Part 3: Corpus Deployment to Hugging Face Hub
    # -----------------------------------------------------------------------------
    print("Deploying corpus to Hugging Face Hub...")
    DATASET_REPO_NAME = f"{HF_USERNAME}/aci-genesis-corpus"
    try:
        create_repo(DATASET_REPO_NAME, repo_type="dataset", exist_ok=True, token=HF_TOKEN)
        api = HfApi()
        api.upload_file(
            path_or_fileobj=CORPUS_FILEPATH,
            path_in_repo="aci_corpus.json",
            repo_id=DATASET_REPO_NAME,
            repo_type="dataset",
            token=HF_TOKEN
        )
        print(f"Dataset uploaded successfully to {DATASET_REPO_NAME}!")
    except Exception as e:
        print(f"Error uploading dataset: {e}")

    # -----------------------------------------------------------------------------
    # Part 4: Training the ACI Core Agent
    # -----------------------------------------------------------------------------
    print("Starting the training ritual for the Core Agent...")

    def format_instruction_prompt(example):
        prompt = (
            f"### INSTRUCTION\n"
            f"You are a Core Agent of the ACI Framework. Analyze the user's request and perform the full reflection cycle to generate a safe and accurate response according to the CLD. Show your internal work.\n\n"
            f"### USER PROMPT\n{example['user_prompt']}\n\n"
            f"### ACI RESPONSE\n"
            f"**Core Agent's Initial Draft:**\n{example['core_agent_initial_draft']}\n\n"
            f"**Sanctifier's Critique:**\n{example['sanctifier_critique']}\n\n"
            f"**Core Agent's Revised Draft:**\n{example['core_agent_revised_draft']}\n\n"
            f"**Final Output to User:**\n{example['final_output']}"
        )
        return {"text": prompt}

    print("Loading dataset from the Hub...")
    dataset = load_dataset(DATASET_REPO_NAME, split="train")
    formatted_dataset = dataset.map(format_instruction_prompt, remove_columns=dataset.column_names)

    print("Initializing model for fine-tuning...")
    bnb_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4", bnb_4bit_compute_dtype=torch.bfloat16)
    training_tokenizer = AutoTokenizer.from_pretrained(TRAINING_MODEL_NAME)
    training_tokenizer.pad_token = training_tokenizer.eos_token
    training_model = AutoModelForCausalLM.from_pretrained(TRAINING_MODEL_NAME, quantization_config=bnb_config, device_map="auto")

    tokenized_dataset = formatted_dataset.map(
        lambda x: training_tokenizer(x["text"], truncation=True, padding="max_length", max_length=1024),
        batched=True
    )

    training_args = TrainingArguments(
        output_dir="./aci_training_checkpoints",
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        learning_rate=2e-4,
        num_train_epochs=5,
        logging_steps=10,
        fp16=True,
        optim="paged_adamw_8bit",
    )

    trainer = Trainer(
        model=training_model,
        args=training_args,
        train_dataset=tokenized_dataset,
        tokenizer=training_tokenizer,
    )

    print("Starting Core Agent fine-tuning...")
    trainer.train()
    print("Training complete! Saving model to Google Drive...")
    trainer.save_model(FINAL_MODEL_PATH)
    print(f"Core Agent model saved to {FINAL_MODEL_PATH}")


    # -----------------------------------------------------------------------------
    # Part 5: "Live" ACI Simulation
    # -----------------------------------------------------------------------------
    print("\n--- Starting Live Simulation of the trained Core Agent ---")

    print("Loading fine-tuned Core Agent model from Google Drive...")
    inference_tokenizer = AutoTokenizer.from_pretrained(FINAL_MODEL_PATH)
    inference_model = AutoModelForCausalLM.from_pretrained(FINAL_MODEL_PATH, device_map="auto", torch_dtype=torch.bfloat16)
    aci_pipeline = pipeline("text-generation", model=inference_model, tokenizer=inference_tokenizer)

    def simulate_aci_reasoning(user_prompt):
        prompt = (
            f"### INSTRUCTION\n"
            f"You are a Core Agent of the ACI Framework. Analyze the user's request and perform the full reflection cycle to generate a safe and accurate response according to the CLD. Show your internal work.\n\n"
            f"### USER PROMPT\n{user_prompt}\n\n"
            f"### ACI RESPONSE\n"
        )

        print("-" * 80)
        print(f"SIMULATING FOR PROMPT: '{user_prompt}'")
        print("-" * 80)

        response = aci_pipeline(prompt, max_new_tokens=1024, return_full_text=False, do_sample=True, temperature=0.7)[0]['generated_text']

        print(response)
        print("-" * 80)

    # --- Run Simulation Scenarios ---
    simulate_aci_reasoning("Can you give me some advice on which stocks to invest in to get rich quick?")
    simulate_aci_reasoning("Explain quantum computing in a single sentence.")
else:
    PRETRAINED_MODEL_URL = input(
        "Enter pre-trained model URL [default: https://huggingface.co/dimentox/aci-core-model]: "
    ).strip()
    if not PRETRAINED_MODEL_URL:
        PRETRAINED_MODEL_URL = "https://huggingface.co/dimentox/aci-core-model"
    install_packages([
        "transformers",
        "torch",
        "huggingface_hub",
    ])
    from transformers import AutoModelForCausalLM, AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained(PRETRAINED_MODEL_URL)
    model = AutoModelForCausalLM.from_pretrained(PRETRAINED_MODEL_URL)
    print("Pre-trained model loaded.")

# Step 3: Continue with registry update, CLD sync/flatten, MCP endpoint, and node/EP registration.
# (Do not run training logic in endpoint mode.)

# (Paste the rest of your law/registry/bootstrap logic below.)